project:
  type: website
  
website: 
  title: "quarto.club"
  description: "A super gallery of quarto websites to help inspire and connect."
  page-navigation: true
  site-url: "https://quarto.club" 
  repo-url: https://github.com/phdjsep/quarto-club 
  repo-actions: []
  google-analytics: "G-YTYTBDF54G"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    
  sidebar:
    title: "quarto.club"
    logo: "assets/img/quarto-club.svg"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/phdjsep/quarto-club
        text: "Github"
    style: "docked"
    search: false
    collapse-level: 1
    contents:
      - href: about.qmd
        text: About Quarto Club
      - href: resources.qmd
        text: Resources

format:
  html:
    theme:
      light: [cosmo, assets/styles/light.scss]
    code-copy: true
    code-overflow: wrap
    toc: false

execute:
  freeze: auto